### PR TITLE
lnbits: add dedicated user and dependencies

### PR DESCRIPTION
**Pull request by openoms**
as discussed in: https://github.com/rootzoll/raspiblitz/pull/1135#issuecomment-619519291

* added modifications to use a non-sudo separate user
* added missing dependencies to the venv: gunicorn and gevent

* fixed typo in menu

### CODE REVIEW

**Comment by openoms** [comment]
Still have a bug in what looks to be the python code (`/home/lnbits/lnbits/lnbits/wallets/opennode.py`):
```
sudo -u lnbits /usr/bin/pipenv run flask migrate
Loading .env environment variables…
Traceback (most recent call last):
  File "/home/lnbits/.local/share/virtualenvs/lnbits-xqYMrTZ5/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/lnbits/.local/share/virtualenvs/lnbits-xqYMrTZ5/lib/python3.7/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/lnbits/.local/share/virtualenvs/lnbits-xqYMrTZ5/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/lnbits/.local/share/virtualenvs/lnbits-xqYMrTZ5/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/lnbits/.local/share/virtualenvs/lnbits-xqYMrTZ5/lib/python3.7/site-packages/click/core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/lnbits/.local/share/virtualenvs/lnbits-xqYMrTZ5/lib/python3.7/site-packages/click/core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/lnbits/.local/share/virtualenvs/lnbits-xqYMrTZ5/lib/python3.7/site-packages/flask/cli.py", line 542, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/home/lnbits/.local/share/virtualenvs/lnbits-xqYMrTZ5/lib/python3.7/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/home/lnbits/.local/share/virtualenvs/lnbits-xqYMrTZ5/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/lnbits/lnbits/lnbits/__init__.py", line 12, in <module>
    from .db import init_databases, open_db
  File "/home/lnbits/lnbits/lnbits/db.py", line 4, in <module>
    from .helpers import ExtensionManager
  File "/home/lnbits/lnbits/lnbits/helpers.py", line 8, in <module>
    from .settings import LNBITS_PATH
  File "/home/lnbits/lnbits/lnbits/settings.py", line 5, in <module>
    WALLET = OpenNodeWallet(endpoint=os.getenv("OPENNODE_API_ENDPOINT"),admin_key=os.getenv("OPENNODE_ADMIN_KEY"),invoice_key=os.getenv("OPENNODE_INVOICE_KEY"))
  File "/home/lnbits/lnbits/lnbits/wallets/opennode.py", line 10, in __init__
    self.endpoint = endpoint[:-1] if endpoint.endswith("/") else endpoint
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by openoms** [comment]
Also the latest lnbits release is at  v0.0.1  (vs 0.1.0 ? )

**Comment by arcbtc** [comment]
Yes, this was the wrong version, v0.0.1
This is the correct version v0.1
https://github.com/lnbits/lnbits/releases/tag/0.1.0

Sorry for the inconvenience!

**Comment by openoms** [comment]
the relevant PR was merged so closing here.

**Comment by eillarra** [comment]
> Still have a bug in what looks to be the python code (`/home/lnbits/lnbits/lnbits/wallets/opennode.py`)

@openoms I think that was a 0.0.1 bug. In 0.1.0 these .env vars are requested only if "OpenNodeWallet" is your preferred backend wallet, as defined by `LNBITS_BACKEND_WALLET_CLASS`. For the RaspiBlitz, this value should be `LndRestWallet` if we are using the REST backend.

**Pull request closed without merging**
